"""initial migration

Revision ID: b2e681541b70
Revises: 
Create Date: 2022-11-13 13:39:14.375823

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2e681541b70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('guid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('group', sa.String(), nullable=False),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guid'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_student_guid'), 'student', ['guid'], unique=True)
    op.create_table('teacher',
    sa.Column('guid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('departament', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('guid'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_teacher_guid'), 'teacher', ['guid'], unique=True)
    op.create_table('year',
    sa.Column('guid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('guid'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_year_guid'), 'year', ['guid'], unique=True)
    op.create_table('record',
    sa.Column('guid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('student_guid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('teacher_guid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('term', sa.Integer(), nullable=False),
    sa.Column('year_guid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('mark', sa.String(), nullable=False),
    sa.Column('exam_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exam_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['student_guid'], ['student.guid'], ),
    sa.ForeignKeyConstraint(['teacher_guid'], ['teacher.guid'], ),
    sa.ForeignKeyConstraint(['year_guid'], ['year.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_record_guid'), 'record', ['guid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_record_guid'), table_name='record')
    op.drop_table('record')
    op.drop_index(op.f('ix_year_guid'), table_name='year')
    op.drop_table('year')
    op.drop_index(op.f('ix_teacher_guid'), table_name='teacher')
    op.drop_table('teacher')
    op.drop_index(op.f('ix_student_guid'), table_name='student')
    op.drop_table('student')
    # ### end Alembic commands ###
